-- V2__add_constraints_and_indexes.sql

ALTER TABLE iam.role_permission ADD CONSTRAINT fk_iam_role_permission_role_id FOREIGN KEY (role_id) REFERENCES iam.role (id) ON DELETE CASCADE;
ALTER TABLE iam.role_permission ADD CONSTRAINT fk_iam_role_permission_permission_id FOREIGN KEY (permission_id) REFERENCES iam.permission (id) ON DELETE CASCADE;
ALTER TABLE iam.user_role ADD CONSTRAINT fk_iam_user_role_user_id FOREIGN KEY (user_id) REFERENCES iam.user_account (id) ON DELETE CASCADE;
ALTER TABLE iam.user_role ADD CONSTRAINT fk_iam_user_role_role_id FOREIGN KEY (role_id) REFERENCES iam.role (id) ON DELETE RESTRICT;
ALTER TABLE iam.mfa_registration ADD CONSTRAINT fk_iam_mfa_registration_user_id FOREIGN KEY (user_id) REFERENCES iam.user_account (id) ON DELETE CASCADE;
ALTER TABLE member.organization_identifier ADD CONSTRAINT fk_member_organization_identifier_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE CASCADE;
ALTER TABLE member.address ADD CONSTRAINT fk_member_address_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE CASCADE;
ALTER TABLE member.address ADD CONSTRAINT fk_member_address_person_id FOREIGN KEY (person_id) REFERENCES member.person (id) ON DELETE CASCADE;
ALTER TABLE member.organization_contact ADD CONSTRAINT fk_member_organization_contact_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE CASCADE;
ALTER TABLE member.organization_contact ADD CONSTRAINT fk_member_organization_contact_person_id FOREIGN KEY (person_id) REFERENCES member.person (id) ON DELETE RESTRICT;
ALTER TABLE member.membership ADD CONSTRAINT fk_member_membership_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE RESTRICT;
ALTER TABLE member.membership_status_history ADD CONSTRAINT fk_member_membership_status_history_membership_id FOREIGN KEY (membership_id) REFERENCES member.membership (id) ON DELETE RESTRICT;
ALTER TABLE member.group_membership ADD CONSTRAINT fk_member_group_membership_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE CASCADE;
ALTER TABLE member.group_membership ADD CONSTRAINT fk_member_group_membership_group_id FOREIGN KEY (group_id) REFERENCES member.professional_group (id) ON DELETE RESTRICT;
ALTER TABLE enrollment.prospect ADD CONSTRAINT fk_enrollment_prospect_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE SET NULL;
ALTER TABLE enrollment.prospect ADD CONSTRAINT fk_enrollment_prospect_assigned_group_id FOREIGN KEY (assigned_group_id) REFERENCES member.professional_group (id) ON DELETE SET NULL;
ALTER TABLE enrollment.enrollment_case ADD CONSTRAINT fk_enrollment_enrollment_case_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE RESTRICT;
ALTER TABLE enrollment.enrollment_review ADD CONSTRAINT fk_enrollment_enrollment_review_case_id FOREIGN KEY (case_id) REFERENCES enrollment.enrollment_case (id) ON DELETE CASCADE;
ALTER TABLE enrollment.enrollment_decision ADD CONSTRAINT fk_enrollment_enrollment_decision_case_id FOREIGN KEY (case_id) REFERENCES enrollment.enrollment_case (id) ON DELETE RESTRICT;
ALTER TABLE contribution.contribution_call ADD CONSTRAINT fk_contribution_contribution_call_membership_id FOREIGN KEY (membership_id) REFERENCES member.membership (id) ON DELETE RESTRICT;
ALTER TABLE contribution.contribution_call ADD CONSTRAINT fk_contribution_contribution_call_fiscal_year_id FOREIGN KEY (fiscal_year_id) REFERENCES contribution.fiscal_year (id) ON DELETE RESTRICT;
ALTER TABLE contribution.installment ADD CONSTRAINT fk_contribution_installment_contribution_call_id FOREIGN KEY (contribution_call_id) REFERENCES contribution.contribution_call (id) ON DELETE CASCADE;
ALTER TABLE contribution.adjustment ADD CONSTRAINT fk_contribution_adjustment_contribution_call_id FOREIGN KEY (contribution_call_id) REFERENCES contribution.contribution_call (id) ON DELETE RESTRICT;
ALTER TABLE payment.payment_reference ADD CONSTRAINT fk_payment_payment_reference_membership_id FOREIGN KEY (membership_id) REFERENCES member.membership (id) ON DELETE RESTRICT;
ALTER TABLE payment.payment_transaction ADD CONSTRAINT fk_payment_payment_transaction_payment_reference_id FOREIGN KEY (payment_reference_id) REFERENCES payment.payment_reference (id) ON DELETE SET NULL;
ALTER TABLE payment.payment_allocation ADD CONSTRAINT fk_payment_payment_allocation_payment_transaction_id FOREIGN KEY (payment_transaction_id) REFERENCES payment.payment_transaction (id) ON DELETE RESTRICT;
ALTER TABLE payment.payment_allocation ADD CONSTRAINT fk_payment_payment_allocation_installment_id FOREIGN KEY (installment_id) REFERENCES contribution.installment (id) ON DELETE RESTRICT;
ALTER TABLE payment.bank_statement_line ADD CONSTRAINT fk_payment_bank_statement_line_statement_id FOREIGN KEY (statement_id) REFERENCES payment.bank_statement (id) ON DELETE CASCADE;
ALTER TABLE payment.reconciliation_case ADD CONSTRAINT fk_payment_reconciliation_case_payment_transaction_id FOREIGN KEY (payment_transaction_id) REFERENCES payment.payment_transaction (id) ON DELETE RESTRICT;
ALTER TABLE payment.reconciliation_case ADD CONSTRAINT fk_payment_reconciliation_case_statement_line_id FOREIGN KEY (statement_line_id) REFERENCES payment.bank_statement_line (id) ON DELETE RESTRICT;
ALTER TABLE receipt.receipt ADD CONSTRAINT fk_receipt_receipt_payment_transaction_id FOREIGN KEY (payment_transaction_id) REFERENCES payment.payment_transaction (id) ON DELETE RESTRICT;
ALTER TABLE receipt.receipt ADD CONSTRAINT fk_receipt_receipt_supersedes_receipt_id FOREIGN KEY (supersedes_receipt_id) REFERENCES receipt.receipt (id) ON DELETE RESTRICT;
ALTER TABLE recovery.sequence_step ADD CONSTRAINT fk_recovery_sequence_step_template_id FOREIGN KEY (template_id) REFERENCES recovery.sequence_template (id) ON DELETE CASCADE;
ALTER TABLE recovery.recovery_case ADD CONSTRAINT fk_recovery_recovery_case_membership_id FOREIGN KEY (membership_id) REFERENCES member.membership (id) ON DELETE RESTRICT;
ALTER TABLE recovery.recovery_case ADD CONSTRAINT fk_recovery_recovery_case_fiscal_year_id FOREIGN KEY (fiscal_year_id) REFERENCES contribution.fiscal_year (id) ON DELETE RESTRICT;
ALTER TABLE recovery.recovery_action ADD CONSTRAINT fk_recovery_recovery_action_recovery_case_id FOREIGN KEY (recovery_case_id) REFERENCES recovery.recovery_case (id) ON DELETE CASCADE;
ALTER TABLE recovery.promise_to_pay ADD CONSTRAINT fk_recovery_promise_to_pay_recovery_case_id FOREIGN KEY (recovery_case_id) REFERENCES recovery.recovery_case (id) ON DELETE CASCADE;
ALTER TABLE incentive.bonus_line ADD CONSTRAINT fk_incentive_bonus_line_calculation_id FOREIGN KEY (calculation_id) REFERENCES incentive.bonus_calculation (id) ON DELETE RESTRICT;
ALTER TABLE incentive.bonus_line ADD CONSTRAINT fk_incentive_bonus_line_payment_transaction_id FOREIGN KEY (payment_transaction_id) REFERENCES payment.payment_transaction (id) ON DELETE RESTRICT;
ALTER TABLE service.request ADD CONSTRAINT fk_service_request_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE RESTRICT;
ALTER TABLE service.request_message ADD CONSTRAINT fk_service_request_message_request_id FOREIGN KEY (request_id) REFERENCES service.request (id) ON DELETE CASCADE;
ALTER TABLE document.document_version ADD CONSTRAINT fk_document_document_version_document_id FOREIGN KEY (document_id) REFERENCES document.document (id) ON DELETE CASCADE;
ALTER TABLE document.document_link ADD CONSTRAINT fk_document_document_link_document_id FOREIGN KEY (document_id) REFERENCES document.document (id) ON DELETE CASCADE;
ALTER TABLE governance.meeting ADD CONSTRAINT fk_governance_meeting_commission_id FOREIGN KEY (commission_id) REFERENCES governance.commission (id) ON DELETE SET NULL;
ALTER TABLE governance.meeting_attendance ADD CONSTRAINT fk_governance_meeting_attendance_meeting_id FOREIGN KEY (meeting_id) REFERENCES governance.meeting (id) ON DELETE CASCADE;
ALTER TABLE governance.meeting_attendance ADD CONSTRAINT fk_governance_meeting_attendance_person_id FOREIGN KEY (person_id) REFERENCES member.person (id) ON DELETE RESTRICT;
ALTER TABLE governance.decision ADD CONSTRAINT fk_governance_decision_meeting_id FOREIGN KEY (meeting_id) REFERENCES governance.meeting (id) ON DELETE SET NULL;
ALTER TABLE governance.decision_action ADD CONSTRAINT fk_governance_decision_action_decision_id FOREIGN KEY (decision_id) REFERENCES governance.decision (id) ON DELETE CASCADE;
ALTER TABLE event.registration ADD CONSTRAINT fk_event_registration_event_id FOREIGN KEY (event_id) REFERENCES event.event (id) ON DELETE CASCADE;
ALTER TABLE event.registration ADD CONSTRAINT fk_event_registration_organization_id FOREIGN KEY (organization_id) REFERENCES member.organization (id) ON DELETE RESTRICT;
ALTER TABLE event.registration ADD CONSTRAINT fk_event_registration_person_id FOREIGN KEY (person_id) REFERENCES member.person (id) ON DELETE SET NULL;
ALTER TABLE notification.delivery_attempt ADD CONSTRAINT fk_notification_delivery_attempt_notification_id FOREIGN KEY (notification_id) REFERENCES notification.notification (id) ON DELETE CASCADE;
ALTER TABLE integration.endpoint_configuration ADD CONSTRAINT fk_integration_endpoint_configuration_partner_id FOREIGN KEY (partner_id) REFERENCES integration.partner (id) ON DELETE CASCADE;
ALTER TABLE integration.webhook_subscription ADD CONSTRAINT fk_integration_webhook_subscription_partner_id FOREIGN KEY (partner_id) REFERENCES integration.partner (id) ON DELETE CASCADE;
ALTER TABLE integration.webhook_delivery ADD CONSTRAINT fk_integration_webhook_delivery_subscription_id FOREIGN KEY (subscription_id) REFERENCES integration.webhook_subscription (id) ON DELETE CASCADE;
ALTER TABLE integration.webhook_delivery ADD CONSTRAINT fk_integration_webhook_delivery_outbox_event_id FOREIGN KEY (outbox_event_id) REFERENCES integration.outbox_event (id) ON DELETE RESTRICT;
ALTER TABLE reporting.report_execution ADD CONSTRAINT fk_reporting_report_execution_report_definition_id FOREIGN KEY (report_definition_id) REFERENCES reporting.report_definition (id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_ref_reference_value_created_by ON ref.reference_value (created_by);
CREATE INDEX IF NOT EXISTS idx_ref_reference_value_updated_by ON ref.reference_value (updated_by);
CREATE INDEX IF NOT EXISTS idx_ref_reference_value_domain ON ref.reference_value (domain);
CREATE INDEX IF NOT EXISTS idx_ref_number_sequence_created_by ON ref.number_sequence (created_by);
CREATE INDEX IF NOT EXISTS idx_ref_number_sequence_updated_by ON ref.number_sequence (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ref_number_sequence_sequence_code ON ref.number_sequence (sequence_code);
CREATE INDEX IF NOT EXISTS idx_iam_user_account_created_by ON iam.user_account (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_user_account_updated_by ON iam.user_account (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_user_account_keycloak_subject ON iam.user_account (keycloak_subject);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_user_account_email ON iam.user_account (email);
CREATE INDEX IF NOT EXISTS idx_iam_user_account_status ON iam.user_account (status);
CREATE INDEX IF NOT EXISTS idx_iam_role_created_by ON iam.role (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_role_updated_by ON iam.role (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_role_code ON iam.role (code);
CREATE INDEX IF NOT EXISTS idx_iam_permission_created_by ON iam.permission (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_permission_updated_by ON iam.permission (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_permission_code ON iam.permission (code);
CREATE INDEX IF NOT EXISTS idx_iam_role_permission_created_by ON iam.role_permission (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_role_permission_updated_by ON iam.role_permission (updated_by);
CREATE INDEX IF NOT EXISTS idx_iam_role_permission_role_id ON iam.role_permission (role_id);
CREATE INDEX IF NOT EXISTS idx_iam_role_permission_permission_id ON iam.role_permission (permission_id);
CREATE INDEX IF NOT EXISTS idx_iam_user_role_created_by ON iam.user_role (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_user_role_updated_by ON iam.user_role (updated_by);
CREATE INDEX IF NOT EXISTS idx_iam_user_role_user_id ON iam.user_role (user_id);
CREATE INDEX IF NOT EXISTS idx_iam_user_role_role_id ON iam.user_role (role_id);
CREATE INDEX IF NOT EXISTS idx_iam_mfa_registration_created_by ON iam.mfa_registration (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_mfa_registration_updated_by ON iam.mfa_registration (updated_by);
CREATE INDEX IF NOT EXISTS idx_iam_mfa_registration_user_id ON iam.mfa_registration (user_id);
CREATE INDEX IF NOT EXISTS idx_iam_access_review_created_by ON iam.access_review (created_by);
CREATE INDEX IF NOT EXISTS idx_iam_access_review_updated_by ON iam.access_review (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_access_review_review_code ON iam.access_review (review_code);
CREATE INDEX IF NOT EXISTS idx_member_person_created_by ON member.person (created_by);
CREATE INDEX IF NOT EXISTS idx_member_person_updated_by ON member.person (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_person_email ON member.person (email);
CREATE INDEX IF NOT EXISTS idx_member_person_phone ON member.person (phone);
CREATE INDEX IF NOT EXISTS idx_member_organization_created_by ON member.organization (created_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_updated_by ON member.organization (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_legal_name ON member.organization (legal_name);
CREATE INDEX IF NOT EXISTS idx_member_organization_sector_code ON member.organization (sector_code);
CREATE INDEX IF NOT EXISTS idx_member_organization_status ON member.organization (status);
CREATE INDEX IF NOT EXISTS idx_member_organization_risk_level ON member.organization (risk_level);
CREATE INDEX IF NOT EXISTS idx_member_organization_identifier_created_by ON member.organization_identifier (created_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_identifier_updated_by ON member.organization_identifier (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_identifier_organization_id ON member.organization_identifier (organization_id);
CREATE INDEX IF NOT EXISTS idx_member_organization_identifier_identifier_value ON member.organization_identifier (identifier_value);
CREATE INDEX IF NOT EXISTS idx_member_address_created_by ON member.address (created_by);
CREATE INDEX IF NOT EXISTS idx_member_address_updated_by ON member.address (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_address_organization_id ON member.address (organization_id);
CREATE INDEX IF NOT EXISTS idx_member_address_person_id ON member.address (person_id);
CREATE INDEX IF NOT EXISTS idx_member_organization_contact_created_by ON member.organization_contact (created_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_contact_updated_by ON member.organization_contact (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_organization_contact_organization_id ON member.organization_contact (organization_id);
CREATE INDEX IF NOT EXISTS idx_member_organization_contact_person_id ON member.organization_contact (person_id);
CREATE INDEX IF NOT EXISTS idx_member_membership_created_by ON member.membership (created_by);
CREATE INDEX IF NOT EXISTS idx_member_membership_updated_by ON member.membership (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_membership_organization_id ON member.membership (organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_member_membership_membership_number ON member.membership (membership_number);
CREATE INDEX IF NOT EXISTS idx_member_membership_category_code ON member.membership (category_code);
CREATE INDEX IF NOT EXISTS idx_member_membership_status ON member.membership (status);
CREATE INDEX IF NOT EXISTS idx_member_membership_status_history_created_by ON member.membership_status_history (created_by);
CREATE INDEX IF NOT EXISTS idx_member_membership_status_history_membership_id ON member.membership_status_history (membership_id);
CREATE INDEX IF NOT EXISTS idx_member_professional_group_created_by ON member.professional_group (created_by);
CREATE INDEX IF NOT EXISTS idx_member_professional_group_updated_by ON member.professional_group (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_member_professional_group_code ON member.professional_group (code);
CREATE INDEX IF NOT EXISTS idx_member_group_membership_created_by ON member.group_membership (created_by);
CREATE INDEX IF NOT EXISTS idx_member_group_membership_updated_by ON member.group_membership (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_group_membership_organization_id ON member.group_membership (organization_id);
CREATE INDEX IF NOT EXISTS idx_member_group_membership_group_id ON member.group_membership (group_id);
CREATE INDEX IF NOT EXISTS idx_member_communication_preference_created_by ON member.communication_preference (created_by);
CREATE INDEX IF NOT EXISTS idx_member_communication_preference_updated_by ON member.communication_preference (updated_by);
CREATE INDEX IF NOT EXISTS idx_member_communication_preference_organization_id ON member.communication_preference (organization_id);
CREATE INDEX IF NOT EXISTS idx_member_communication_preference_person_id ON member.communication_preference (person_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_prospect_created_by ON enrollment.prospect (created_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_prospect_updated_by ON enrollment.prospect (updated_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_prospect_organization_id ON enrollment.prospect (organization_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_prospect_assigned_group_id ON enrollment.prospect (assigned_group_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_prospect_status ON enrollment.prospect (status);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_case_created_by ON enrollment.enrollment_case (created_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_case_updated_by ON enrollment.enrollment_case (updated_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_case_organization_id ON enrollment.enrollment_case (organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_enrollment_enrollment_case_case_number ON enrollment.enrollment_case (case_number);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_case_status ON enrollment.enrollment_case (status);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_case_assigned_to ON enrollment.enrollment_case (assigned_to);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_review_created_by ON enrollment.enrollment_review (created_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_review_case_id ON enrollment.enrollment_review (case_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_decision_created_by ON enrollment.enrollment_decision (created_by);
CREATE INDEX IF NOT EXISTS idx_enrollment_enrollment_decision_case_id ON enrollment.enrollment_decision (case_id);
CREATE INDEX IF NOT EXISTS idx_contribution_fiscal_year_created_by ON contribution.fiscal_year (created_by);
CREATE INDEX IF NOT EXISTS idx_contribution_fiscal_year_updated_by ON contribution.fiscal_year (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_contribution_fiscal_year_year ON contribution.fiscal_year (year);
CREATE INDEX IF NOT EXISTS idx_contribution_rate_rule_created_by ON contribution.rate_rule (created_by);
CREATE INDEX IF NOT EXISTS idx_contribution_rate_rule_updated_by ON contribution.rate_rule (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_contribution_rate_rule_rule_code ON contribution.rate_rule (rule_code);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_created_by ON contribution.contribution_call (created_by);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_updated_by ON contribution.contribution_call (updated_by);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_membership_id ON contribution.contribution_call (membership_id);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_fiscal_year_id ON contribution.contribution_call (fiscal_year_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_contribution_contribution_call_call_number ON contribution.contribution_call (call_number);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_due_date ON contribution.contribution_call (due_date);
CREATE INDEX IF NOT EXISTS idx_contribution_contribution_call_status ON contribution.contribution_call (status);
CREATE INDEX IF NOT EXISTS idx_contribution_installment_created_by ON contribution.installment (created_by);
CREATE INDEX IF NOT EXISTS idx_contribution_installment_updated_by ON contribution.installment (updated_by);
CREATE INDEX IF NOT EXISTS idx_contribution_installment_contribution_call_id ON contribution.installment (contribution_call_id);
CREATE INDEX IF NOT EXISTS idx_contribution_installment_due_date ON contribution.installment (due_date);
CREATE INDEX IF NOT EXISTS idx_contribution_installment_status ON contribution.installment (status);
CREATE INDEX IF NOT EXISTS idx_contribution_adjustment_created_by ON contribution.adjustment (created_by);
CREATE INDEX IF NOT EXISTS idx_contribution_adjustment_contribution_call_id ON contribution.adjustment (contribution_call_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_contribution_adjustment_adjustment_number ON contribution.adjustment (adjustment_number);
CREATE INDEX IF NOT EXISTS idx_payment_payment_reference_created_by ON payment.payment_reference (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_payment_reference_updated_by ON payment.payment_reference (updated_by);
CREATE INDEX IF NOT EXISTS idx_payment_payment_reference_membership_id ON payment.payment_reference (membership_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_payment_reference_reference_value ON payment.payment_reference (reference_value);
CREATE INDEX IF NOT EXISTS idx_payment_payment_transaction_created_by ON payment.payment_transaction (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_payment_transaction_payment_reference_id ON payment.payment_transaction (payment_reference_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_payment_transaction_transaction_number ON payment.payment_transaction (transaction_number);
CREATE INDEX IF NOT EXISTS idx_payment_payment_transaction_provider_transaction_id ON payment.payment_transaction (provider_transaction_id);
CREATE INDEX IF NOT EXISTS idx_payment_payment_transaction_paid_at ON payment.payment_transaction (paid_at);
CREATE INDEX IF NOT EXISTS idx_payment_payment_transaction_status ON payment.payment_transaction (status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_payment_transaction_idempotency_key ON payment.payment_transaction (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_payment_payment_allocation_created_by ON payment.payment_allocation (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_payment_allocation_payment_transaction_id ON payment.payment_allocation (payment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_payment_payment_allocation_installment_id ON payment.payment_allocation (installment_id);
CREATE INDEX IF NOT EXISTS idx_payment_provider_event_created_by ON payment.provider_event (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_provider_event_partner_code ON payment.provider_event (partner_code);
CREATE INDEX IF NOT EXISTS idx_payment_provider_event_processing_status ON payment.provider_event (processing_status);
CREATE INDEX IF NOT EXISTS idx_payment_bank_statement_created_by ON payment.bank_statement (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_bank_statement_updated_by ON payment.bank_statement (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_bank_statement_statement_ref ON payment.bank_statement (statement_ref);
CREATE INDEX IF NOT EXISTS idx_payment_bank_statement_line_created_by ON payment.bank_statement_line (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_bank_statement_line_statement_id ON payment.bank_statement_line (statement_id);
CREATE INDEX IF NOT EXISTS idx_payment_bank_statement_line_booking_date ON payment.bank_statement_line (booking_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_bank_statement_line_fingerprint ON payment.bank_statement_line (fingerprint);
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_case_created_by ON payment.reconciliation_case (created_by);
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_case_updated_by ON payment.reconciliation_case (updated_by);
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_case_payment_transaction_id ON payment.reconciliation_case (payment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_case_statement_line_id ON payment.reconciliation_case (statement_line_id);
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_case_status ON payment.reconciliation_case (status);
CREATE INDEX IF NOT EXISTS idx_receipt_receipt_created_by ON receipt.receipt (created_by);
CREATE INDEX IF NOT EXISTS idx_receipt_receipt_payment_transaction_id ON receipt.receipt (payment_transaction_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_receipt_receipt_receipt_number ON receipt.receipt (receipt_number);
CREATE INDEX IF NOT EXISTS idx_receipt_receipt_issued_at ON receipt.receipt (issued_at);
CREATE INDEX IF NOT EXISTS idx_recovery_campaign_created_by ON recovery.campaign (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_campaign_updated_by ON recovery.campaign (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recovery_campaign_campaign_code ON recovery.campaign (campaign_code);
CREATE INDEX IF NOT EXISTS idx_recovery_campaign_status ON recovery.campaign (status);
CREATE INDEX IF NOT EXISTS idx_recovery_sequence_template_created_by ON recovery.sequence_template (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_sequence_template_updated_by ON recovery.sequence_template (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recovery_sequence_template_code ON recovery.sequence_template (code);
CREATE INDEX IF NOT EXISTS idx_recovery_sequence_step_created_by ON recovery.sequence_step (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_sequence_step_updated_by ON recovery.sequence_step (updated_by);
CREATE INDEX IF NOT EXISTS idx_recovery_sequence_step_template_id ON recovery.sequence_step (template_id);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_created_by ON recovery.recovery_case (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_updated_by ON recovery.recovery_case (updated_by);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_membership_id ON recovery.recovery_case (membership_id);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_fiscal_year_id ON recovery.recovery_case (fiscal_year_id);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_assigned_to ON recovery.recovery_case (assigned_to);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_case_status ON recovery.recovery_case (status);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_action_created_by ON recovery.recovery_action (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_action_recovery_case_id ON recovery.recovery_action (recovery_case_id);
CREATE INDEX IF NOT EXISTS idx_recovery_recovery_action_action_at ON recovery.recovery_action (action_at);
CREATE INDEX IF NOT EXISTS idx_recovery_promise_to_pay_created_by ON recovery.promise_to_pay (created_by);
CREATE INDEX IF NOT EXISTS idx_recovery_promise_to_pay_updated_by ON recovery.promise_to_pay (updated_by);
CREATE INDEX IF NOT EXISTS idx_recovery_promise_to_pay_recovery_case_id ON recovery.promise_to_pay (recovery_case_id);
CREATE INDEX IF NOT EXISTS idx_recovery_promise_to_pay_promised_date ON recovery.promise_to_pay (promised_date);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_rule_created_by ON incentive.bonus_rule (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_rule_updated_by ON incentive.bonus_rule (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_incentive_bonus_rule_rule_code ON incentive.bonus_rule (rule_code);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_calculation_created_by ON incentive.bonus_calculation (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_calculation_updated_by ON incentive.bonus_calculation (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_line_created_by ON incentive.bonus_line (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_line_calculation_id ON incentive.bonus_line (calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_line_payment_transaction_id ON incentive.bonus_line (payment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_incentive_bonus_line_beneficiary_user_id ON incentive.bonus_line (beneficiary_user_id);
CREATE INDEX IF NOT EXISTS idx_incentive_revenue_share_statement_created_by ON incentive.revenue_share_statement (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_revenue_share_statement_updated_by ON incentive.revenue_share_statement (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_financial_dispute_created_by ON incentive.financial_dispute (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_financial_dispute_updated_by ON incentive.financial_dispute (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_financial_dispute_object_id ON incentive.financial_dispute (object_id);
CREATE INDEX IF NOT EXISTS idx_service_sla_policy_created_by ON service.sla_policy (created_by);
CREATE INDEX IF NOT EXISTS idx_service_sla_policy_updated_by ON service.sla_policy (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_sla_policy_request_type ON service.sla_policy (request_type);
CREATE INDEX IF NOT EXISTS idx_service_request_created_by ON service.request (created_by);
CREATE INDEX IF NOT EXISTS idx_service_request_updated_by ON service.request (updated_by);
CREATE INDEX IF NOT EXISTS idx_service_request_organization_id ON service.request (organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_request_request_number ON service.request (request_number);
CREATE INDEX IF NOT EXISTS idx_service_request_request_type ON service.request (request_type);
CREATE INDEX IF NOT EXISTS idx_service_request_status ON service.request (status);
CREATE INDEX IF NOT EXISTS idx_service_request_assigned_to ON service.request (assigned_to);
CREATE INDEX IF NOT EXISTS idx_service_request_due_at ON service.request (due_at);
CREATE INDEX IF NOT EXISTS idx_service_request_message_created_by ON service.request_message (created_by);
CREATE INDEX IF NOT EXISTS idx_service_request_message_request_id ON service.request_message (request_id);
CREATE INDEX IF NOT EXISTS idx_document_document_created_by ON document.document (created_by);
CREATE INDEX IF NOT EXISTS idx_document_document_updated_by ON document.document (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_document_document_code ON document.document (document_code);
CREATE INDEX IF NOT EXISTS idx_document_document_category_code ON document.document (category_code);
CREATE INDEX IF NOT EXISTS idx_document_document_version_created_by ON document.document_version (created_by);
CREATE INDEX IF NOT EXISTS idx_document_document_version_document_id ON document.document_version (document_id);
CREATE INDEX IF NOT EXISTS idx_document_document_link_created_by ON document.document_link (created_by);
CREATE INDEX IF NOT EXISTS idx_document_document_link_updated_by ON document.document_link (updated_by);
CREATE INDEX IF NOT EXISTS idx_document_document_link_document_id ON document.document_link (document_id);
CREATE INDEX IF NOT EXISTS idx_document_document_link_entity_id ON document.document_link (entity_id);
CREATE INDEX IF NOT EXISTS idx_governance_commission_created_by ON governance.commission (created_by);
CREATE INDEX IF NOT EXISTS idx_governance_commission_updated_by ON governance.commission (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_governance_commission_code ON governance.commission (code);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_created_by ON governance.meeting (created_by);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_updated_by ON governance.meeting (updated_by);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_commission_id ON governance.meeting (commission_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_governance_meeting_meeting_number ON governance.meeting (meeting_number);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_attendance_created_by ON governance.meeting_attendance (created_by);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_attendance_updated_by ON governance.meeting_attendance (updated_by);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_attendance_meeting_id ON governance.meeting_attendance (meeting_id);
CREATE INDEX IF NOT EXISTS idx_governance_meeting_attendance_person_id ON governance.meeting_attendance (person_id);
CREATE INDEX IF NOT EXISTS idx_governance_decision_created_by ON governance.decision (created_by);
CREATE INDEX IF NOT EXISTS idx_governance_decision_updated_by ON governance.decision (updated_by);
CREATE INDEX IF NOT EXISTS idx_governance_decision_meeting_id ON governance.decision (meeting_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_governance_decision_decision_number ON governance.decision (decision_number);
CREATE INDEX IF NOT EXISTS idx_governance_decision_action_created_by ON governance.decision_action (created_by);
CREATE INDEX IF NOT EXISTS idx_governance_decision_action_updated_by ON governance.decision_action (updated_by);
CREATE INDEX IF NOT EXISTS idx_governance_decision_action_decision_id ON governance.decision_action (decision_id);
CREATE INDEX IF NOT EXISTS idx_governance_decision_action_owner_user_id ON governance.decision_action (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_event_event_created_by ON event.event (created_by);
CREATE INDEX IF NOT EXISTS idx_event_event_updated_by ON event.event (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_event_event_event_code ON event.event (event_code);
CREATE INDEX IF NOT EXISTS idx_event_registration_created_by ON event.registration (created_by);
CREATE INDEX IF NOT EXISTS idx_event_registration_updated_by ON event.registration (updated_by);
CREATE INDEX IF NOT EXISTS idx_event_registration_event_id ON event.registration (event_id);
CREATE INDEX IF NOT EXISTS idx_event_registration_organization_id ON event.registration (organization_id);
CREATE INDEX IF NOT EXISTS idx_event_registration_person_id ON event.registration (person_id);
CREATE INDEX IF NOT EXISTS idx_notification_template_created_by ON notification.template (created_by);
CREATE INDEX IF NOT EXISTS idx_notification_template_updated_by ON notification.template (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_notification_template_template_code ON notification.template (template_code);
CREATE INDEX IF NOT EXISTS idx_notification_notification_created_by ON notification.notification (created_by);
CREATE INDEX IF NOT EXISTS idx_notification_notification_updated_by ON notification.notification (updated_by);
CREATE INDEX IF NOT EXISTS idx_notification_notification_status ON notification.notification (status);
CREATE INDEX IF NOT EXISTS idx_notification_notification_scheduled_at ON notification.notification (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_notification_notification_correlation_id ON notification.notification (correlation_id);
CREATE INDEX IF NOT EXISTS idx_notification_delivery_attempt_created_by ON notification.delivery_attempt (created_by);
CREATE INDEX IF NOT EXISTS idx_notification_delivery_attempt_notification_id ON notification.delivery_attempt (notification_id);
CREATE INDEX IF NOT EXISTS idx_notification_delivery_attempt_attempted_at ON notification.delivery_attempt (attempted_at);
CREATE INDEX IF NOT EXISTS idx_integration_partner_created_by ON integration.partner (created_by);
CREATE INDEX IF NOT EXISTS idx_integration_partner_updated_by ON integration.partner (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_integration_partner_partner_code ON integration.partner (partner_code);
CREATE INDEX IF NOT EXISTS idx_integration_endpoint_configuration_created_by ON integration.endpoint_configuration (created_by);
CREATE INDEX IF NOT EXISTS idx_integration_endpoint_configuration_updated_by ON integration.endpoint_configuration (updated_by);
CREATE INDEX IF NOT EXISTS idx_integration_endpoint_configuration_partner_id ON integration.endpoint_configuration (partner_id);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_event_created_by ON integration.outbox_event (created_by);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_event_aggregate_id ON integration.outbox_event (aggregate_id);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_event_status ON integration.outbox_event (status);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_event_available_at ON integration.outbox_event (available_at);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_subscription_created_by ON integration.webhook_subscription (created_by);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_subscription_updated_by ON integration.webhook_subscription (updated_by);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_subscription_partner_id ON integration.webhook_subscription (partner_id);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_delivery_created_by ON integration.webhook_delivery (created_by);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_delivery_subscription_id ON integration.webhook_delivery (subscription_id);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_delivery_outbox_event_id ON integration.webhook_delivery (outbox_event_id);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_delivery_next_attempt_at ON integration.webhook_delivery (next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_audit_audit_event_created_by ON audit.audit_event (created_by);
CREATE INDEX IF NOT EXISTS idx_audit_audit_event_actor_user_id ON audit.audit_event (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_audit_event_action_code ON audit.audit_event (action_code);
CREATE INDEX IF NOT EXISTS idx_audit_audit_event_entity_id ON audit.audit_event (entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_audit_event_correlation_id ON audit.audit_event (correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_security_event_created_by ON audit.security_event (created_by);
CREATE INDEX IF NOT EXISTS idx_audit_security_event_user_id ON audit.security_event (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_security_event_event_type ON audit.security_event (event_type);
CREATE INDEX IF NOT EXISTS idx_audit_security_event_severity ON audit.security_event (severity);
CREATE INDEX IF NOT EXISTS idx_audit_security_event_status ON audit.security_event (status);
CREATE INDEX IF NOT EXISTS idx_audit_data_export_created_by ON audit.data_export (created_by);
CREATE INDEX IF NOT EXISTS idx_audit_data_export_requested_by ON audit.data_export (requested_by);
CREATE INDEX IF NOT EXISTS idx_reporting_report_definition_created_by ON reporting.report_definition (created_by);
CREATE INDEX IF NOT EXISTS idx_reporting_report_definition_updated_by ON reporting.report_definition (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_reporting_report_definition_report_code ON reporting.report_definition (report_code);
CREATE INDEX IF NOT EXISTS idx_reporting_report_execution_created_by ON reporting.report_execution (created_by);
CREATE INDEX IF NOT EXISTS idx_reporting_report_execution_updated_by ON reporting.report_execution (updated_by);
CREATE INDEX IF NOT EXISTS idx_reporting_report_execution_report_definition_id ON reporting.report_execution (report_definition_id);
CREATE INDEX IF NOT EXISTS idx_reporting_report_execution_requested_by ON reporting.report_execution (requested_by);
CREATE INDEX IF NOT EXISTS idx_reporting_report_execution_status ON reporting.report_execution (status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ref_reference_value_domain_code ON ref.reference_value (domain, code);
CREATE UNIQUE INDEX IF NOT EXISTS uq_iam_role_permission ON iam.role_permission (role_id, permission_id);
CREATE INDEX IF NOT EXISTS idx_iam_user_role_scope ON iam.user_role (scope_type, scope_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_member_identifier_type_value ON member.organization_identifier (identifier_type, identifier_value);
CREATE UNIQUE INDEX IF NOT EXISTS uq_member_group_membership_active ON member.group_membership (organization_id, group_id, joined_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_contribution_installment_no ON contribution.installment (contribution_call_id, installment_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_provider_event ON payment.provider_event (partner_code, external_event_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_bank_line ON payment.bank_statement_line (statement_id, line_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_version ON document.document_version (document_id, version_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_notification_attempt ON notification.delivery_attempt (notification_id, attempt_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_webhook_delivery_attempt ON integration.webhook_delivery (subscription_id, outbox_event_id, attempt_no);
ALTER TABLE contribution.contribution_call ADD CONSTRAINT ck_contribution_call_amounts CHECK (amount_due >= 0 AND balance_amount >= 0);
ALTER TABLE contribution.installment ADD CONSTRAINT ck_installment_amounts CHECK (amount_due >= 0 AND amount_paid >= 0);
ALTER TABLE contribution.adjustment ADD CONSTRAINT ck_adjustment_positive CHECK (amount > 0);
ALTER TABLE payment.payment_transaction ADD CONSTRAINT ck_payment_positive CHECK (amount > 0);
ALTER TABLE payment.payment_allocation ADD CONSTRAINT ck_allocation_positive CHECK (allocated_amount > 0);
ALTER TABLE payment.bank_statement_line ADD CONSTRAINT ck_bank_line_nonzero CHECK (amount <> 0);
ALTER TABLE incentive.bonus_rule ADD CONSTRAINT ck_bonus_rate CHECK (rate >= 0);
ALTER TABLE incentive.bonus_line ADD CONSTRAINT ck_bonus_line_amounts CHECK (base_amount >= 0 AND rate >= 0 AND bonus_amount >= 0);
ALTER TABLE event.event ADD CONSTRAINT ck_event_dates CHECK (end_at IS NULL OR end_at >= start_at);
