apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpm-api
  namespace: cnpm-platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpm-api-config
  namespace: cnpm-platform
data:
  SPRING_PROFILES_ACTIVE: production
  TZ: Africa/Bamako
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: cnpm-platform
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
